# basic options
        title: Hisfantor's Blog
        author: Hisfantor
        email: niclas@hisfantor.com
        description: do stuff, make stuff, stop procrastinate
        twitter_username: hisfantor
        github_username:  hisfantor

# build settings
        markdown: kramdown
        theme: minima
        host: 0.0.0.0
        port: 4000
<<<<<<< HEAD
=======

>>>>>>> fe30d46dec757b36d300677b219a82a7c71e4a70

theme: jekyll-theme-minimal